version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "85:80"
      - "445:445"
    volumes:
      - ./src:/var/www/html/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html/src
    ports:
      - "9000:9000"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: vhiweb-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vhiweb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pai
      MYSQL_PASSWORD: passwordpai
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3312:3306"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
